name: ears33
channels:
- conda-forge
- defaults

dependencies:
- numpy
- pandas
- matplotlib
- seaborn
- geopandas
- shapely
- geemap
- rasterio
- jupyterlab
- earthengine-api
- pip

- pip:
  - dataretrieval